---
title: "Exploratory Analysis for MoTR Reading Data"
output: html_notebook
---

```{r}
shhh <- suppressPackageStartupMessages # It's a library, so shhh!

shhh(library( mgcv ))
shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(lme4))
shhh(library(tidymv))
shhh(library(gamlss))
shhh(library(gsubfn))
shhh(library(lmerTest))
shhh(library(tidyverse))
shhh(library(boot))
shhh(library(rsample))
shhh(library(plotrix))
shhh(library(ggrepel))
shhh(library(mgcv))

library(jglmm)
options(JULIA_HOME = "/Applications/Julia-1.8.app/Contents/Resources/julia/bin/")
jglmm_setup()

theme_set(theme_bw())
options(digits=4)
options(scipen=999)
set.seed(444)
pipe_message = function(.data, status) {message(status); .data}

```


# Read in MoTR Data

```{r}

rate = 160

file_prefix = "/Users/ethan/Desktop/motr_lc_160/"
fnames = list.files(path=file_prefix)

# Read in the data
df = data.frame()
for (f in fnames) {
  temp = read.csv(paste0(file_prefix, "/", f)) %>%
    mutate(subj = str_remove(f, "_reading_measures.csv")) %>%
    rename(go_past_time = go_pass_time)
  df = rbind(df, temp)
}

filter_df = df %>%
  group_by(para_nr, subj) %>%
    summarise(correct = if_else(unique(correctness) == 1, 1, 0)) %>%
  ungroup() %>%
  drop_na() %>%
  group_by(subj) %>%
    summarise(p_correct = mean(correct)) %>%
  ungroup() %>%
  mutate(p_correct = round(p_correct, digits = 2))

filter_df %>%
  filter(p_correct < 0.8)

raw_df = df %>%
  filter(correctness == 1) %>%
  mutate(subj = str_remove(subj, "reader_")) %>%
  mutate(subj = as.integer(subj)) %>%
  # Filter out participants who were bots
  filter(! subj %in% c(118, 119, 120, 107, 103, 130, 6, 19) ) %>%
  # See below for filtering out reading measures that are super long
  dplyr::select(expr_id, cond_id, para_nr, word, word_nr, first_duration, total_duration, gaze_duration, go_past_time, FPReg, subj)

raw_df

#length(unique(table(raw_df$subj)))
```

```{r}

motr_df = raw_df %>%
  gather(metric, value, 6:10) %>%
  mutate(condition = case_when(
    cond_id == 1 ~ "no_comma",
    cond_id == 2 ~ "comma",
    cond_id == 3 ~ "high",
    cond_id == 4 ~ "low",
    cond_id == 5 ~ "high",
    cond_id == 6 ~ "low",
    cond_id == 8 ~ "filler"
  )) %>%
  mutate(experiment = case_when(
    cond_id %in% c(1, 2) ~ "Coordination",
    cond_id %in% c(3, 4) ~ "Adverb",
    cond_id %in% c(5, 6) ~ "Relative Clause",
    cond_id %in% c(8) ~ "Filler"
  )) %>%
  rename(item_id = para_nr) %>%
  dplyr::select(-cond_id, -expr_id)
  
# Average across subjects
motr_agg_df = motr_df %>%
  drop_na() %>%
  group_by(experiment, condition, item_id, word, word_nr, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup() %>%
  arrange(experiment, condition, item_id, word_nr)

motr_agg_df

```

## Coordination Experiments

```{r, echo=F}

motr_coord_df = motr_df %>%
  filter(experiment == "Coordination") %>%
  # There's one item that has off indexing -- need to remove it
  mutate(crit = if_else(word == "and", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(crit = if_else(item_id %in% c(45), crit + 1, crit + 2)) %>%
  mutate(word_nr = word_nr - crit) %>%
  # Filter out non-zero words
  mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
  filter(zero == F)

agg_motr_coord_df = motr_coord_df %>%
  filter(word_nr >=-3, word_nr <= 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()


motr_coord_stats_df = data.frame()
for(i in 0:2) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg")){
    temp_df = motr_coord_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj), condition = if_else(condition == "comma", 1, 0))
    if (m == "FPReg") {
      #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df, family = "binomial")
      #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
      #pval = nums[length(nums)]
      model = glmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df, family = "binomial")
      pval = coef(summary(model))[8]
    } else {
      temp_df = temp_df %>% mutate(value = scale(value)) #scale real-valued numbers for lmer
      #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df)
      #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
      #pval = nums[length(nums)]
      model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
      pval = coef(summary(model))[10]
    }
    #estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval)
    motr_coord_stats_df = rbind(motr_coord_stats_df, result_df)
  }
}

motr_coord_plotting_df = merge(agg_motr_coord_df, motr_coord_stats_df, all=T, by = c("word_nr", "metric")) %>%
  group_by(metric) %>%
    mutate(max_y = max(upper),
           min_y = min(lower)) %>%
  ungroup() %>%
  mutate(max_y = max_y + max_y / 10,
         min_y = min_y - min_y / 10,
         sig_y = max_y - max_y / 20)

```

```{r}

motr_coord_plotting_df %>%
  mutate(metric = factor(metric, levels = c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg"),
                         labels = c("First Duration", "Gaze Duration", "Go Past Time", "Total Duration", "First Pass Regression (prob)"))) %>%
  mutate(sig = case_when( pval >= 0.1 ~ " ",
                      pval < 0.10 &  pval >= 0.05 ~ ".",
                      pval < 0.05 & pval >= 0.01  ~ "*",
                      pval < 0.01 & pval >= 0.001  ~ "**",
                      pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
    geom_rect(aes(xmin = -0.5, xmax = 2.5, ymin=min_y, ymax=max_y), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.1) +
    geom_line() +
    geom_text(aes(label = sig, y = sig_y), color = "black") +
    #geom_text(aes(label = sig, y = max_y + (max_y/9)), color = "black") +
  ylab("Reading Time") +
  xlab(" ") +
  scale_x_continuous(breaks=-3:4, labels=c("and", "the", "designer", "took", "a", "bow", "after", "the")) +
  facet_wrap(.~metric, scales="free_y", nrow=2) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave(paste0("../visualization/fix_threshold/coord_", rate, ".pdf"), device="pdf", width = 8, height = 5)

```

## Relative Clause Experiments

```{r}

motr_rc_df = motr_df %>%
  filter(experiment == "Relative Clause") %>%
  mutate(crit = if_else(word == "himself" | word == "herself", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(word_nr = word_nr - crit) %>%
  mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
  filter(zero == F) %>%
  mutate(word_nr = as.integer(word_nr))

agg_motr_rc_df = motr_rc_df %>%
  filter(word_nr >= -3, word_nr <= 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()


motr_rc_stats_df = data.frame()
for(i in 0:2) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg")){
    temp_df = motr_rc_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj), condition = if_else(condition == "high", 1, 0))
     if (m == "FPReg") {
        #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df, family = "binomial")
        #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
        #pval = nums[length(nums)]
        model = glmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df, family = "binomial")
        pval = coef(summary(model))[8]
      } else {
        #temp_df = temp_df %>% mutate(value = scale(value)) #scale real-valued numbers for lmer
        #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df)
        #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
        #pval = nums[length(nums)]
        model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
        pval = coef(summary(model))[10]
      }
    estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval)
    motr_rc_stats_df = rbind(motr_rc_stats_df, result_df)
  }
}

motr_rc_plotting_df = merge(agg_motr_rc_df, motr_rc_stats_df, all=T, by = c("word_nr", "metric")) %>%
    group_by(metric) %>%
    mutate(max_y = max(upper),
           min_y = min(lower)) %>%
  ungroup() %>%
  mutate(max_y = max_y + max_y / 10,
         min_y = min_y - min_y / 10,
         sig_y = max_y - max_y / 15)

```


```{r}

motr_rc_plotting_df %>%
  mutate(metric = factor(metric, levels = c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg"),
                         labels = c("First Duration", "Gaze Duration", "Go Past Time", "Total Duration", "First Pass Regression (prob)"))) %>%
  mutate(sig = case_when( pval >= 0.1 ~ " ",
                      pval < 0.10 &  pval >= 0.05 ~ ".",
                      pval < 0.05 & pval >= 0.01  ~ "*",
                      pval < 0.01 & pval >= 0.001  ~ "**",
                      pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
        geom_rect(aes(xmin = -0.5, xmax = 2.5, ymin=min_y, ymax=max_y), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.1) +
    geom_line() +
    geom_text(aes(label = sig, y = sig_y), color = "black") +
    #geom_text(aes(label = sig, y = max_y + (max_y/9)), color = "black") +
  ylab("Reading Time") +
  xlab(" ") +
  scale_x_continuous(breaks=-3:4, labels=c( "woman", "who", "got", "himself\n herself", "a", "boat", "was", "always")) +
  facet_wrap(.~metric, scales="free_y") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave(paste0("../visualization/fix_threshold/rc_", rate, ".pdf"), device="pdf", width = 8, height = 5)

  
```


```{r}
motr_adv_df = motr_df %>%
  filter(experiment == "Adverb") %>%
  mutate(crit = if_else(word == "last" | word == "next" | word == "yesterday" | word == "tomorrow", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(word_nr = word_nr - crit)  %>%
  mutate(word_nr = as.integer(word_nr))  %>%
  mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
  filter(zero == F) #%>%
  #mutate(word_nr = if_else(word_nr < 0 & word_nr >= -4, as.integer(-1), as.integer(word_nr)),
         #word_nr = if_else(word_nr > 2 & word_nr <= 4, as.integer(3), as.integer(word_nr))) %>%
 # group_by(condition, item_id, subj, word_nr, metric) %>%
    #summarise(value = mean(value)) %>%
  #ungroup()

agg_motr_adv_df = motr_adv_df %>%
  filter(word_nr >= -3, word_nr <= 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()

motr_adv_stats_df = data.frame()
for(i in 0:2) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg")){
    temp_df = motr_adv_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj), condition = if_else(condition == "high", 1, 0))
      if (m == "FPReg") {
        #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df, family = "binomial")
        #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
        #pval = nums[length(nums)]
        model = glmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df, family = "binomial")
        pval = coef(summary(model))[8]
      } else {
        temp_df = temp_df %>% mutate(value = scale(value)) #scale real-valued numbers for lmer
        #model = jglmm(value ~ condition + (condition | subj) + (condition | item_id), data = temp_df)
        #nums = str_extract_all(as.character(summary(model)), "[0-9]+.[0-9]+")[[1]]
        #pval = nums[length(nums)]
        model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
        pval = coef(summary(model))[10]
      }
    estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval)
    motr_adv_stats_df = rbind(motr_adv_stats_df, result_df)
  }
}

motr_adv_plotting_df = merge(agg_motr_adv_df, motr_adv_stats_df, all=T, by = c("word_nr", "metric"))%>%
    group_by(metric) %>%
    mutate(max_y = max(upper),
           min_y = min(lower)) %>%
  ungroup() %>%
  mutate(max_y = max_y + max_y / 10,
         min_y = min_y - min_y / 10,
         sig_y = max_y - max_y / 20)

```

```{r}

motr_adv_plotting_df %>%
  mutate(metric = factor(metric, levels = c("first_duration", "gaze_duration", "go_past_time", "total_duration", "FPReg"),
                         labels = c("First Duration", "Gaze Duration", "Go Past Time", "Total Duration", "First Pass Regression (prob)"))) %>%
  mutate(sig = case_when( pval >= 0.05 ~ " ",
                        pval < 0.05 & pval >= 0.01  ~ "*",
                        pval < 0.01 & pval >= 0.001  ~ "**",
                        pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
    geom_rect(aes(xmin = -0.5, xmax = 2.5, ymin = if_else(metric=="First Pass Regression (prob)", 0, 300), ymax = if_else(metric=="First Pass Regression (prob)", 0.2, 850)), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) +
    geom_line() +
    geom_text(aes(label = sig, y = if_else(metric=="First Pass Regression (prob)", 0.16, 800)), color = "black") +
    #geom_text(aes(label = " ", y = if_else(metric=="First Pass Regression (prob)", 0.17, 750))) +
  ylab("Reading Time") +
  xlab("Condition") +
  scale_x_continuous(breaks=-3:4, labels=c("that", "she", "took", "last/next", "week,", "but", "she", "was")) +
  facet_wrap(.~metric, scales="free_y") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave(paste0("../visualization/fix_threshold/adv_", rate, ".pdf"), device="pdf", width = 8, height = 5)


```




