---
title: "Exploratory Analysis for MoTR Reading Data"
output: html_notebook
---

```{r}
shhh <- suppressPackageStartupMessages # It's a library, so shhh!

shhh(library( mgcv ))
shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(lme4))
shhh(library(tidymv))
shhh(library(gamlss))
shhh(library(gsubfn))
shhh(library(lmerTest))
shhh(library(tidyverse))
shhh(library(boot))
shhh(library(rsample))
shhh(library(plotrix))
shhh(library(ggrepel))
shhh(library(mgcv))

shhh(library(brms))
shhh(library(bayesplot))
shhh(library(patchwork))
shhh(library(MASS))
shhh(library(tidyr))
shhh(library(extraDistr))
shhh(library(purrr))
# For exercises with Stan code
shhh(library(rstan))
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = FALSE)

library(car)
library(coda)
shhh(library(gridExtra))

theme_set(theme_bw())
options(digits=4)
options(scipen=999)
set.seed(444)
pipe_message = function(.data, status) {message(status); .data}

```


# Read in MoTR Data

```{r}

rate = 160

file_prefix = "../reading_measures/provo/provo_f160/"
fnames = list.files(path=file_prefix)

df = data.frame()
for (f in fnames) {
  temp = read.csv(paste0(file_prefix, "/", f)) %>%
    mutate(subj = str_remove(f, "_reading_measures.csv"))
  df = rbind(df, temp)
}

# Filter out readers who don't answer the comprehension questions correctly
filter_df = df %>%
  group_by(para_nr, subj) %>% summarise(correct = if_else(unique(correctness) == 1, 1, 0)) %>% ungroup() %>%
  drop_na() %>%
  group_by(subj) %>% summarise(p_correct = mean(correct)) %>% ungroup() %>%
  mutate(p_correct = round(p_correct, digits = 2))

filter_df = filter_df %>% filter(p_correct < 0.8)
filter_list = filter_df$subj
## reader_3:0.70, reader_60:0.79, reader_76:0.72 , reader_256:0.71 , reader_262:0.57 

raw_df = df %>%
  filter(! subj %in% c(filter_list)) %>%
  mutate(word = str_trim(word)) %>%
  mutate(subj = str_remove(subj, "reader_")) %>%
  mutate(subj = as.character(subj)) %>%
  # filter(! subj %in% c("3", "60", "76", "256", "262")) %>% # Explanation for this filtering
  mutate(FPReg = if_else(total_duration == 0, -1, FPReg)) %>% #If the word is skipped we can't say that it wasn't regressed on the first pass. Set to a "NA"
  dplyr::select(expr_id, cond_id, para_nr, word, word_nr, first_duration, total_duration, gaze_duration, go_past_time, FPReg, subj)

length(unique(raw_df$subj))

df %>%
  filter(! subj %in% c(filter_list)) %>%
  filter(FPReg >= 0) %>%
  dplyr::select(FPReg) %>%
  drop_na() %>%
  summarise( m = mean(FPReg))

df %>%
  filter(! subj %in% c(filter_list)) %>%
  dplyr::select(FPFix) %>%
  drop_na() %>%
  summarise( m = mean(FPFix))


```


```{r}
# Average across subjects
motr_agg_df = raw_df %>%
  gather(metric, value, 6:10) %>%
    filter(value >= 0) %>% #Removes the "NA" values for FPReg
  
    # ==== Remove skipped words
    # mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
    # filter(zero == F) %>%
  
    drop_na() %>%
    group_by(para_nr, word_nr, word, metric) %>% 
      mutate(outlier = if_else(metric != "FPReg" & value > (mean(value) + 3 * sd(value)), T, F)) %>% filter(outlier == F) %>%
      summarise(value = mean(value), nsubj = length(unique(subj))) %>%
  ungroup() %>%
  arrange(para_nr, word_nr) %>%
  rename(text_id = para_nr, word_text_idx = word_nr, motr_value = value)

# View(motr_agg_df)
# write.csv(motr_agg_df, file = "/Users/cui/Desktop/MoTR/pipeline/ancillary_data/motr_agg_df.csv", row.names = FALSE)

```




# Comparison to Provo


```{r}
# Read in Provo surprisal, frequency and length data
provo_modeling_df = read.csv("../ancillary_data/provo_df.csv") %>%
  dplyr::select(text_id, sent_id, trigger_idx, word, freq, surp, len) %>%
  rename(word_idx = trigger_idx)

provo_modeling_df
# View(provo_modeling_df)

```

```{r}
# Read in Provo eyetracking data

provo_raw_df = read.csv("../ancillary_data/provo_eyetracking.csv")

```

```{r}

# unique(provo_raw_df$Participant_ID)
# length(unique(provo_raw_df$Participant_ID))

provo_eyetracking_df = provo_raw_df %>%
  dplyr::select(Participant_ID, Text_ID, Sentence_Number, Word_In_Sentence_Number, Word, Word_Number, IA_FIRST_FIX_PROGRESSIVE, IA_FIRST_RUN_DWELL_TIME, IA_DWELL_TIME, IA_REGRESSION_PATH_DURATION, IA_REGRESSION_OUT, IA_SKIP) %>%
  rename( #first_duration = IA_FIRST_FIXATION_DURATION,   
          gaze_duration = IA_FIRST_RUN_DWELL_TIME,
          total_duration = IA_DWELL_TIME,
          go_past_time = IA_REGRESSION_PATH_DURATION,
          subj = Participant_ID,
          text_id = Text_ID,
          sent_id = Sentence_Number,
          word_idx = Word_In_Sentence_Number,
          word_text_idx = Word_Number,   # IA_ID?
          word = Word,      # Word?
          FPReg = IA_REGRESSION_OUT,
          skip = IA_SKIP,
          ff_progressive = IA_FIRST_FIX_PROGRESSIVE) %>%
  mutate(first_duration = gaze_duration) %>%
  mutate(gaze_duration = if_else(ff_progressive == 0, 0, as.double(gaze_duration)),
         go_past_time = if_else(ff_progressive == 0, 0, as.double(go_past_time))) %>%
  dplyr::select(-ff_progressive) %>%
  
  mutate(
    gaze_duration = if_else(total_duration == 0, 0, as.double(gaze_duration)),
      go_past_time = if_else(total_duration == 0, 0, as.double(go_past_time)),
      FPReg = if_else(total_duration == 0, -1, as.double(FPReg)),
      first_duration =  if_else(total_duration == 0, 0, as.double(first_duration)),
  ) %>%
  
  # drop_na() %>%     # will drop the whole row with all the metrics
  gather(metric, value, 7:12) %>%
  filter(value >= 0) %>%          # filter skipped word in eye tracking data for FPReg
  # ==== Remove skipped words
  # mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
  # filter(zero == F) %>%
  
  # mutate(value = if_else(is.na(value), as.integer(0), as.integer(value))) %>%
  # mutate(value = if_else(metric != "FPReg" & is.na(value), as.integer(0), as.integer(value))) %>%
  drop_na() %>%
  mutate(word = str_trim(word)) %>%
  mutate(subj = str_remove(subj, "Sub")) %>%
  mutate(subj = as.integer(subj)) %>%
    group_by(text_id, word_text_idx, sent_id, word_idx, word, metric) %>%
    mutate(outlier = if_else(metric != "FPReg" & metric != "skip" & value > (mean(value) + 3 * sd(value) ), T, F)) %>%
    filter(outlier == F) %>%
  ungroup() #%>%

# Aggregate cross-participant data for all subjects
provo_eyetracking_agg_df = provo_eyetracking_df %>%
  group_by(text_id, word_text_idx, sent_id, word_idx, word, metric) %>%
    summarise(value = mean(value),
              nsubj = length(unique(subj))) %>%
    ungroup()

# View(provo_eyetracking_df)

# View(provo_eyetracking_agg_df)
# write.csv(provo_eyetracking_agg_df, file = "/Users/cui/Desktop/MoTR/pipeline/ancillary_data/provo_eyetracking_agg_df.csv", row.names = FALSE)

provo_raw_df %>%
  dplyr::select(IA_REGRESSION_OUT) %>%
  drop_na() %>%
  summarise( m = mean(IA_REGRESSION_OUT))

provo_raw_df %>%
  dplyr::select(IA_SKIP) %>%
  drop_na() %>%
  summarise( m = mean(IA_SKIP))


```

```{r}

# Split the eyetracking data in two by subjects to see how well it correlates with itself
provo_eyetracking_subj1_df_temp = provo_eyetracking_df %>%
  filter(subj <= 42) %>%
  mutate(word_text_idx = as.integer(word_text_idx - 1)) %>%
  group_by(text_id, word_text_idx, sent_id, word_idx, word, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup() %>%
  rename(value_1 = value) #%>%
  # dplyr::select(-sent_id, -word_idx)

# View(provo_eyetracking_subj1_df_temp)

provo_eyetracking_subj1_df = merge(provo_eyetracking_subj1_df_temp, motr_agg_df, by=c("text_id", "word_text_idx", "metric")) %>%
  arrange(text_id, sent_id, word_idx) %>%
  filter(!(text_id == 13 & word_text_idx >= 20 & word_text_idx <= 52)) %>%
  filter(!(text_id == 3 & word_text_idx >= 46 & word_text_idx <= 57)) %>%
  rename(word = word.y) %>%
  dplyr::select(text_id, word_text_idx, metric, word, value_1)

# View(provo_eyetracking_subj1_df)

provo_eyetracking_subj2_df = provo_eyetracking_df %>%
  filter(subj > 42) %>%
  mutate(word_text_idx = as.integer(word_text_idx - 1)) %>%
  group_by(text_id, word_text_idx, sent_id, word_idx, word, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup() %>%
    rename(value_2 = value)%>%
  dplyr::select(-sent_id, -word_idx)

# View(provo_eyetracking_subj2_df)
  
provo_eyetr_grouped_df = merge(provo_eyetracking_subj2_df, provo_eyetracking_subj1_df, by=c("text_id", "word_text_idx", "metric")) %>%
  # filter(word.x == word.y) %>%
  dplyr::select(-word.y) %>%
  group_by(metric) %>%
    mutate(motr_outlier = if_else(metric != "FPReg" & metric != "skip" & value_1 > (mean(value_1) + 3 * sd(value_1) ), T, F)) %>%
    filter(motr_outlier == F) %>%
    mutate(eyetr_outlier = if_else(metric != "FPReg" & metric != "skip" & value_2 > (mean(value_2) + 3 * sd(value_2) ), T, F)) %>%
    filter(eyetr_outlier == F) %>%
  ungroup() %>%
  gather(measure, value, c("value_1", "value_2")) %>%
  dplyr::select(-motr_outlier, -eyetr_outlier)

# View(provo_eyetr_grouped_df)

```


```{r}
provo_df = merge(provo_eyetracking_agg_df, provo_modeling_df, by=c("text_id", "sent_id", "word_idx")) %>%
  mutate(word_text_idx = as.integer(word_text_idx - 1)) %>%
  arrange(text_id, sent_id, word_idx) %>%
  rename(eyetr_value = value) 

provo_df = merge(provo_df, motr_agg_df, by=c("text_id", "word_text_idx", "metric")) %>%
arrange(text_id, sent_id, word_idx) %>%
  # almost all the word.x != word.y is because of normalization problem, so we can keep them, instead, deleting some special cases
filter(!(text_id == 13 & word_text_idx >= 20 & word_text_idx <= 52)) %>%
  filter(!(text_id == 3 & word_text_idx >= 46 & word_text_idx <= 57)) %>%
# filter(word.x == word) #%>%
dplyr::select(-word.x, -word.y) %>%
group_by(metric) %>%
  mutate(motr_outlier = if_else(metric != "FPReg" & motr_value > (mean(motr_value) + 3 * sd(motr_value) ), T, F)) %>%
  filter(motr_outlier == F) %>%
  mutate(eyetr_outlier = if_else(metric != "FPReg" & eyetr_value > (mean(eyetr_value) + 3 * sd(eyetr_value) ), T, F)) %>%
  filter(eyetr_outlier == F) %>%
ungroup() %>%
gather(measure, value, c("eyetr_value", "motr_value")) %>%
dplyr::select(-motr_outlier, -eyetr_outlier)
  
# View(provo_df)
# provo_df
```


# Bayesian -- use Stan -- motr & eyetr correlation

```{r}
priors_cor_motr_eyetr <- c(
  prior(normal(0, 10), class = Intercept),
  prior(uniform(-1, 1), class = b),
  prior(normal(0, 10), class = sigma)
)

fit_cor = function(df, drop_zero, met, comparison) {
  if (comparison == "motr_eyetr" | comparison == "eyetr_eyetr") {
    model = brms::brm( scale(motr_value) ~ 1 + scale(eyetr_value), 
                      data = df,
                      chains = 4,
                      family = gaussian(),
                      file = paste0("./bayesian_models_cor/cor_lm/", comparison, "_", met, "_drop", drop_zero),
                      cores = 4,
                      backend = "cmdstanr",
                      prior = priors_cor_motr_eyetr,
                      warmup = 2000,
                      iter = 6000,
                      control = list(adapt_delta = 0.999),
                      save_pars = save_pars(all = TRUE)
                      )
    brm_cor = fixef(model)[2]
    brm_crl2.5 = fixef(model)[6]
    brm_crl97.5 = fixef(model)[8]
    brm_sd = fixef(model)[4]
    
    pearson_r <- cor.test(df$eyetr_value, df$motr_value)
    prs_cor = pearson_r$estimate
    prs_CI2.5 = (pearson_r$conf.int)[1]
    prs_CI97.5 = (pearson_r$conf.int)[2]
    prs_p_value = pearson_r$p.value
    
    cor_lm <- lm(scale(motr_value) ~ 1 + scale(eyetr_value), data = df)
    lm_coef <- coef(cor_lm)
    est_conf_interval <- confint(cor_lm)[2,]
    lm_cor = lm_coef[2]
    lm_CI2.5 = est_conf_interval[1]
    lm_CI97.5 = est_conf_interval[2]
    lm_p_value = summary(cor_lm)$coefficients[2, 4]
    
  } else{
      model = brms::brm( scale(motr_value) ~ 1 + scale(stat), 
                    data = df,
                    chains = 4,
                    family = gaussian(),
                    file = paste0("./bayesian_models_cor/cor_lm/", comparison, "_", met, "_drop", drop_zero),
                    cores = 4,
                    backend = "cmdstanr",
                    prior = priors_cor_motr_eyetr,
                    warmup = 2000,
                    iter = 6000,
                    control = list(adapt_delta = 0.999),
                    save_pars = save_pars(all = TRUE)
                    )
      brm_cor = fixef(model)[2]
      brm_crl2.5 = fixef(model)[6]
      brm_crl97.5 = fixef(model)[8]
      brm_sd = fixef(model)[4]
      
      pearson_r <- cor.test(df$motr_value, df$stat)
      prs_cor = pearson_r$estimate
      prs_CI2.5 = (pearson_r$conf.int)[1]
      prs_CI97.5 = (pearson_r$conf.int)[2]
      prs_p_value = pearson_r$p.value
      
      cor_lm <- lm(scale(motr_value) ~ 1 + scale(stat), data = df)
      lm_coef <- coef(cor_lm)
      est_conf_interval <- confint(cor_lm)[2,]
      lm_cor = lm_coef[2]
      lm_CI2.5 = est_conf_interval[1]
      lm_CI97.5 = est_conf_interval[2]
      lm_p_value = summary(cor_lm)$coefficients[2, 4]
  }
  
  
  result_df = data.frame(comparison = comparison, metrics = met, drop_zeros = drop_zero, 
                         prs_cor = prs_cor, prs_CI2.5 = prs_CI2.5, prs_CI97.5 = prs_CI97.5, prs_p_value = prs_p_value, 
                         lm_cor = lm_cor, lm_CI2.5 = lm_CI2.5, lm_CI97.5 = lm_CI97.5, lm_p_value = lm_p_value,
                         brm_cor = brm_cor, brm_crl2.5 = brm_crl2.5, brm_crl97.5 = brm_crl97.5, brm_sd = brm_sd)
  return(result_df)
  
}
```



```{r}
provo_cor_stat_brm_lm_df = data.frame()

for (comp in c("motr_eyetr", "eyetr_eyetr")) {
  for (m in c("gaze_duration", "go_past_time", "total_duration", "FPReg")) {
    for (drop0s in c(F, T)) {
      if (drop0s==F) {
        if (comp == "motr_eyetr") {
          dummy_df = provo_df %>% filter(metric == m) %>% spread(measure, value)
        } else {
          dummy_df =  provo_eyetr_grouped_df %>% filter(metric == m) %>% distinct() %>%
            filter(!(row_number() %in% c(443, 444, 445, 446))) %>% spread(measure, value) %>%
            rename(eyetr_value = value_1, motr_value = value_2)
        }
      } else {
        if (comp == "motr_eyetr") {
          dummy_df = provo_df %>% filter(metric == m) %>% spread(measure, value) %>% filter(eyetr_value > 0, motr_value > 0)
        } else {
          dummy_df = provo_eyetr_grouped_df %>% filter(metric == "gaze_duration") %>% distinct() %>%
            filter(!(row_number() %in% c(443, 444, 445, 446))) %>% spread(measure, value) %>%
            filter(value_1 > 0, value_2 > 0) %>% rename(eyetr_value = value_1, motr_value = value_2)
        }
      }
      write.csv(dummy_df, paste0("./provo_temp/", comp, "_", m, "_", drop0s, ".csv"), row.names = FALSE)
      # View(dummy_df)
      # comp_results = dummy_df %>% fit_cor(., drop_zero = drop0s, met = m, comparison = comp)
      # provo_cor_stat_brm_lm_df = rbind(provo_cor_stat_brm_lm_df, comp_results)
    }
  }
}

for (comp in c("motr_stats", "eyetr_stats")) {
  for (m in c("freq", "len", "surp")) { 
    drop0s = F
    if (comp == "motr_stats") {
      dummy_df = provo_df %>% filter(metric == "gaze_duration") %>% spread(measure, value) %>% mutate(stat = .data[[m]])
    } else {
      dummy_df =  provo_df %>% filter(metric == "gaze_duration") %>% spread(measure, value) %>% dplyr::select(-motr_value) %>%
        rename(motr_value=eyetr_value) %>% mutate(stat = .data[[m]])
    }
    write.csv(dummy_df, paste0("./provo_temp/", comp, "_", m, "_", drop0s, ".csv"), row.names = FALSE)
    # View(dummy_df)
    # comp_results = dummy_df %>% fit_cor(., drop_zero = drop0s, met = m, comparison = comp)
    # provo_cor_stat_brm_lm_df = rbind(provo_cor_stat_brm_lm_df, comp_results)

  }
}

# write.csv(provo_cor_stat_brm_lm_df, "provo_cor_stats_all_3methods.csv", row.names = FALSE)
# 
# View(provo_cor_stat_brm_lm_df)

```



