---
title: "Exploratory Analysis for MoTR Reading Data"
output: html_notebook
---

```{r}
shhh <- suppressPackageStartupMessages # It's a library, so shhh!

shhh(library( mgcv ))
shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(lme4))
shhh(library(tidymv))
shhh(library(gamlss))
shhh(library(gsubfn))
shhh(library(lmerTest))
shhh(library(tidyverse))
shhh(library(boot))
shhh(library(rsample))
shhh(library(plotrix))
shhh(library(ggrepel))
shhh(library(mgcv))

theme_set(theme_bw())
options(digits=4)
options(scipen=999)
set.seed(444)
pipe_message = function(.data, status) {message(status); .data}

```

```{r}

```

# Read in MoTR Data

```{r}

file_prefix = "../reading_measures/cleaned_f160"
fnames = list.files(path=file_prefix)

# Read in the data
df = data.frame()
for (f in fnames) {
  temp = read.csv(paste0(file_prefix, "/", f)) %>%
    mutate(subj = str_remove(f, "_reading_measures.csv")) %>%
    dplyr::select(expr_id, cond_id, para_nr, word, word_nr, first_duration, total_duration,
                  gaze_duration, go_pass_time, FPReg, subj) %>%
      rename(go_past_time = go_pass_time)
  df = rbind(df, temp)
}

motr_df = df %>%
  mutate(expr_id = if_else(expr_id == 1, "Attachment", "Provo")) %>%
  gather(metric, value, 6:10)

motr_df

```

```{r}
# Average across subjects
motr_agg_df = motr_df %>%
  drop_na() %>%
  group_by(expr_id, cond_id, para_nr, word, word_nr, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup() %>%
  arrange(expr_id, cond_id, para_nr, word_nr)

motr_agg_df

```

```{r}

motr_provo_df = motr_agg_df %>%
  filter(expr_id == "Provo") %>%
  rename(text_id = para_nr,
         word_text_idx = word_nr,
         motr_value = value) %>%
  dplyr::select(-expr_id, -cond_id)

```



# Comparison to Provo


```{r}
# Read in Provo surprisal, frequency and length data
provo_modeling_df = read.csv("../ancillary_data/provo_df.csv") %>%
  dplyr::select(text_id, sent_id, trigger_idx, word, freq, surp, len) %>%
  rename(word_idx = trigger_idx)

provo_modeling_df

```

```{r}
# Read in Provo eyetracking data

provo_raw_df = read.csv("../ancillary_data/provo_eyetracking.csv")

provo_eyetracking_df = provo_raw_df %>%
  dplyr::select(Participant_ID, Text_ID, Sentence_Number, Word_In_Sentence_Number, Word, IA_ID, IA_FIRST_FIX_PROGRESSIVE, IA_FIRST_FIXATION_DURATION, IA_FIRST_RUN_DWELL_TIME, IA_DWELL_TIME, IA_REGRESSION_PATH_DURATION, IA_REGRESSION_OUT) %>%
  rename( first_duration = IA_FIRST_FIXATION_DURATION,
          gaze_duration = IA_FIRST_RUN_DWELL_TIME,
          total_duration = IA_DWELL_TIME,
          go_past_time = IA_REGRESSION_PATH_DURATION,
          subj = Participant_ID,
          text_id = Text_ID,
          sent_id = Sentence_Number,
          word_idx = Word_In_Sentence_Number,
          word_text_idx = IA_ID,  # better than word number
          word = Word,
          FPReg = IA_REGRESSION_OUT,
          ff_progressive = IA_FIRST_FIX_PROGRESSIVE) %>%
  mutate(gaze_duration = ifelse(ff_progressive == 0, 0, gaze_duration),
         go_past_time = ifelse(ff_progressive == 0, 0, go_past_time)) %>%
  dplyr::select(-ff_progressive) %>%
  gather(metric, value, 7:11) %>%
  mutate(value = if_else(is.na(value), as.integer(0), as.integer(value))) %>%
  drop_na() %>%
  group_by(text_id, word_text_idx, sent_id, word_idx, word, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup()

provo_eyetracking_df

```


```{r}
provo_df = merge(provo_eyetracking_df, provo_modeling_df, by=c("text_id", "sent_id", "word_idx")) %>%
  mutate(word_text_idx = as.integer(word_text_idx - 1)) %>%
  arrange(text_id, sent_id, word_idx)

provo_df = merge(provo_df, motr_provo_df, by=c("text_id", "word_text_idx", "metric")) %>%
  rename(eyetr_value = value) %>%
  arrange(text_id, sent_id, word_idx) %>%
  filter(word.x == word) %>%
  dplyr::select(-word.x, -word.y) %>%
  mutate(motr_outlier = if_else(motr_value > (mean(motr_value) + 3 * sd(motr_value) ), T, F)) %>%
  filter(motr_outlier == F) %>%
  gather(measure, value, c("eyetr_value", "motr_value")) %>%
  # filter(metric != "first_duration") %>%
  filter(metric != "FPReg")


```

```{r}
provo_df %>%
  ggplot(aes(x = value, color=metric)) +
    geom_density() +
    facet_wrap(.~measure) +
    xlab("Reading Measure")
ggsave("../visualization/density.png", device = "png", width = 6, height = 2.5)
```



```{r}

gd_df = provo_df %>% filter(metric == "total_duration") %>% spread(measure, value)
cor.test(gd_df$eyetr_value, gd_df$motr_value)

provo_df %>%
  spread(measure, value) %>%
  ggplot(aes(x = motr_value, y=eyetr_value, color=metric)) +
    geom_point(alpha = 0.2) +
    facet_wrap(.~metric, scales="free") +
    geom_smooth()

ggsave("../visualization/metric_cor.png", device = "png", width = 6, height = 2.5)
```


```{r}
provo_df %>%
  gather(word_prop, word_prop_val, c("freq", "len", "surp")) %>%
  filter(metric == "gaze_duration") %>%
  ggplot(aes(x = value, y=word_prop_val, color = measure)) +
    geom_point(alpha = 0.2) +
    facet_grid(word_prop~measure, scales="free") +
    geom_smooth() +
    xlab("Reading Measure")

ggsave("../visualization/word_prop_comps.png", device = "png", width = 6, height = 3)

```

```{r}
provo_df %>%
  ggplot(aes(x = value, y=freq, color=metric)) +
    geom_point(alpha = 0.2) +
    facet_grid(metric~measure, scales="free") +
    geom_smooth()
```

```{r}
provo_df %>%
  ggplot(aes(x = value, y=surp, color=metric)) +
    geom_point(alpha = 0.2) +
    facet_grid(metric~measure, scales="free") +
    geom_smooth()
```


## Shape of surprisal / RT relationship

```{r}

fit_gam_inner = function(bootstrap_sample, mean_predictors) {
  
  df = bootstrap_sample$data
  weights = tabulate(as.integer(bootstrap_sample), nrow(df))
  
  m = gam(psychometric ~ s(surp, bs = 'cr', k = 6) + s(prev_surp, bs = 'cr', k = 6) + te(freq, len, bs = 'cr') + te(prev_freq, prev_len, bs = 'cr'), data = df, weights = weights)
  terms_to_predict = c("s(surp)", "s(prev_surp)")
  
  newdata = data.frame(surp=seq(0,20,by=0.1), prev_surp=mean_predictors$surp,
                       freq=mean_predictors$freq, prev_freq=mean_predictors$freq,
                       len=mean_predictors$freq, prev_len=mean_predictors$freq)

  # Returns a matrix N_samples * N_terms.
  per_term_predictions = predict(m, newdata=newdata, terms=terms_to_predict, type="terms")

  # Additive model -- sum across predictor response contributions (matrix columns).
  predictions = rowSums(per_term_predictions)

  return(newdata %>% mutate(y=predictions))
}

fit_gam = function(df, mean_predictors, alpha=0.05) {
  # Bootstrap-resample data
  boot_models = df %>% bootstraps(times=10) %>% 
   # Fit a GAM and get predictions for each sample
    mutate(smoothed=map(splits, fit_gam_inner, mean_predictors=mean_predictors))
  
  # Extract mean and 5% and 95% percentile y-values for each surprisal value
  result = boot_models %>% 
    unnest(smoothed) %>% 
    dplyr::select(surp, y) %>% 
    group_by(surp) %>% 
      summarise(y_lower=quantile(y, alpha / 2), 
                y_upper=quantile(y, 1 - alpha / 2),
                y=mean(y)) %>% 
    ungroup()
  
  return (result)
}

```


```{r}

gam_modeling_df = provo_df %>%
  spread(measure, value) %>%
  mutate(len = nchar(word)) %>%
  group_by(metric, text_id) %>%
    arrange(word_text_idx) %>%
    mutate(prev_surp = lag(surp),
           prev_freq = lag(freq),
           prev_len = lag(len),
           prev_eyetr_value = lag(eyetr_value)) %>%
  ungroup() %>%
  drop_na() %>%
  rename(psychometric = motr_value)


smooths_df = data.frame()

metrics = c("gaze_duration", "total_duration", "go_past_time", "first_duration")
for (m in metrics) {
  print(paste0("Fitting model for ", m))
  dummy_df = gam_modeling_df %>% filter(metric == m)
  mean_predictors = dummy_df %>% summarise(surp = mean(surp), len = mean(len), freq = mean(freq))
  smooths = dummy_df %>% fit_gam(., mean_predictors)
  #Fix 0 surprisal = 0 ms
  gam_smooths = smooths %>% mutate(delta = 0 - y[1], y=y + delta, y_lower= y_lower + delta, y_upper=y_upper + delta)
  smooths_df = rbind(smooths_df, gam_smooths %>% mutate(psychometric = m))
}

```


```{r}

# Surprisal curves
  ggplot() +
      geom_line(data = smooths_df, aes(x=surp, y=y, color = psychometric), size=0.7) +
      geom_ribbon(data = smooths_df, aes(x=surp, ymin=y_lower, ymax=y_upper, fill = psychometric), alpha=0.3, size=0.5) +
      scale_x_continuous(labels=c(0, 10, 20), breaks=c(0, 10, 20), minor_breaks = NULL) +
      facet_wrap(psychometric~.) +
      ylab("Slowdown due to Surprisal (ms)") +
      xlab("Surprisal of Word") +
      ggtitle("Relationship between MoTR Times and Surprisal")
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  )


```




# Targeted Evaluation Data

# Read in MoTR Data

```{r}

file_prefix = "/Users/ethan/Desktop/motr_results/"
fnames = list.files(path=file_prefix)

# Read in the data
df = data.frame()
for (f in fnames) {
  temp = read.csv(paste0(file_prefix, "/", f)) %>%
    mutate(subj = str_remove(f, "_reading_measures.csv")) %>%
    rename(go_past_time = go_pass_time)
  df = rbind(df, temp)
}

raw_df = df %>%
  filter(correctness == 1) %>%
  mutate(subj = str_remove(subj, "reader_")) %>%
  mutate(subj = as.integer(subj)) %>%
  filter(! subj %in% c(118, 119, 120, 107, 103, 130, 6, 19) ) %>%
  # See below for filtering out reading measures that are super long
  dplyr::select(expr_id, cond_id, para_nr, word, word_nr, first_duration, total_duration, gaze_duration, go_past_time, FPReg, subj)

raw_df

#length(unique(table(raw_df$subj)))
```

```{r}

motr_df = raw_df %>%
  gather(metric, value, 6:10) %>%
  mutate(condition = case_when(
    cond_id == 1 ~ "no_comma",
    cond_id == 2 ~ "comma",
    cond_id == 3 ~ "high",
    cond_id == 4 ~ "low",
    cond_id == 5 ~ "high",
    cond_id == 6 ~ "low",
    cond_id == 8 ~ "filler"
  )) %>%
  mutate(experiment = case_when(
    cond_id %in% c(1, 2) ~ "Coordination",
    cond_id %in% c(3, 4) ~ "Adverb",
    cond_id %in% c(5, 6) ~ "Relative Clause",
    cond_id %in% c(8) ~ "Filler"
  )) %>%
  rename(item_id = para_nr) %>%
  dplyr::select(-cond_id, -expr_id)
  
# Average across subjects
motr_agg_df = motr_df %>%
  drop_na() %>%
  group_by(experiment, condition, item_id, word, word_nr, metric) %>%
    summarise(value = mean(value)) %>%
  ungroup() %>%
  arrange(experiment, condition, item_id, word_nr)

motr_agg_df

table(motr_df$item_id)

```

```{r}

motr_coord_df = motr_df %>%
  filter(experiment == "Coordination") %>%
  # There's one item that has off indexing -- need to remove it
  mutate(crit = if_else(word == "and", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(crit = if_else(item_id %in% c(45), crit + 1, crit + 2)) %>%
  mutate(word_nr = word_nr - crit) %>%
  mutate(zero = if_else(metric != "FPReg" & value == 0,T, F)) %>%
  filter(zero == F)

agg_motr_coord_df = motr_coord_df %>%
  filter(word_nr >-5, word_nr < 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()


motr_coord_stats_df = data.frame()
for(i in -3:3) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration")){
    temp_df = motr_coord_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj)) %>%
      mutate(condition = if_else(condition == "comma", 1, 0)) %>%
      mutate(value = scale(value)) 
    model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
    pval = coef(summary(model))[10]
    estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval, est = estimate)
    motr_coord_stats_df = rbind(motr_coord_stats_df, result_df)
  }
}

motr_coord_plotting_df = merge(agg_motr_coord_df, motr_coord_stats_df, all=T, by = c("word_nr", "metric"))

motr_coord_plotting_df %>%
  mutate(sig = case_when( pval >= 0.05 ~ " ",
                      pval < 0.05 & pval >= 0.01  ~ "*",
                      pval < 0.01 & pval >= 0.001  ~ "**",
                      pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
    #geom_rect(aes(xmin = -0.5, xmax = 3.5, ymin = 300, ymax = 800), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) +
    geom_line() +
    geom_text(aes(label = sig, y = if_else(metric=="FPReg", 0, 700)), color = "black") +
    geom_text(aes(label = " ", y = if_else(metric=="FPReg", 0, 750))) +
    #geom_text(aes(label = word, y = if_else(cond_id == "Comma", 3000, 3500)), size = 2) +
    #facet_grid(para_nr~cond_id) +
  ylab("Reading Time") +
  xlab("Condition") +
  scale_x_continuous(breaks=-4:3, labels=c("man", "and/,and", "his", "wife", "ran", "away", "from", "the")) +
  facet_wrap(.~metric, scales="free_y") +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}

motr_rc_df = motr_df %>%
  filter(experiment == "Relative Clause") %>%
  mutate(crit = if_else(word == "himself" | word == "herself", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(word_nr = word_nr - crit) #%>%
  #mutate(zero = if_else(metric != "FPReg" & value == 0, T, F)) %>%
  #filter(zero == F)

agg_motr_rc_df = motr_rc_df %>%
  filter(word_nr >= -4, word_nr < 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()


motr_rc_stats_df = data.frame()
for(i in -3:3) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration")){
    temp_df = motr_rc_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj)) %>%
      mutate(condition = if_else(condition == "high", 1, 0)) %>%
      mutate(value = scale(value)) 
    model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
    pval = coef(summary(model))[10]
    estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval, est = estimate)
    motr_rc_stats_df = rbind(motr_rc_stats_df, result_df)
  }
}

motr_rc_plotting_df = merge(agg_motr_rc_df, motr_rc_stats_df, all=T, by = c("word_nr", "metric"))

motr_rc_plotting_df %>%
  mutate(sig = case_when( pval >= 0.05 ~ " ",
                        pval < 0.05 & pval >= 0.01  ~ "*",
                        pval < 0.01 & pval >= 0.001  ~ "**",
                        pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
    #geom_rect(aes(xmin = 2.5, xmax = 5.5, ymin = 100, ymax = 800), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) +
    geom_line() +
    geom_text(aes(label = sig, y = if_else(metric=="FPReg", 0, 700)), color = "black") +
    geom_text(aes(label = " ", y = if_else(metric=="FPReg", 0, 750))) +
    #geom_text(aes(label = word, y = if_else(cond_id == "Comma", 3000, 3500)), size = 2) +
    #facet_grid(para_nr~cond_id) +
  ylab("Reading Time") +
  xlab("Condition") +
  scale_x_continuous(breaks=-4:3, labels=c("the", "fisherman", "who", "got", "himself\n herself", "a", "boat", "was")) +
  facet_wrap(.~metric, scales="free_y") +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
  
```

```{r}
motr_adv_df = motr_df %>%
  filter(experiment == "Adverb") %>%
  mutate(crit = if_else(word == "last" | word == "next" | word == "yesterday" | word == "tomorrow", word_nr, as.integer(0) )) %>%
  group_by(condition, item_id) %>%
    mutate(crit = unique(crit)[2]) %>%
  ungroup() %>%
  mutate(word_nr = word_nr - crit) %>%
  mutate(zero = if_else(metric != "FPReg" & value == 0, T, F)) %>%
  filter(zero == F)

agg_motr_adv_df = motr_adv_df %>%
  filter(word_nr >= -4, word_nr < 4) %>%
  drop_na() %>%
  group_by(condition, word_nr, metric) %>%
    summarise( m = mean(value),
               sd = std.error(value),
               upper = m + 1.96 * sd,
               lower = m - 1.98 * sd,
               n = n()) %>%
  ungroup()

motr_adv_stats_df = data.frame()
for(i in -3:3) {
  for(m in c("first_duration", "gaze_duration", "go_past_time", "total_duration")){
    temp_df = motr_adv_df %>% filter(metric == m) %>% filter(word_nr == i) %>%
      mutate(item_id = as.factor(item_id), subj = as.factor(subj)) %>%
      mutate(condition = if_else(condition == "high", 1, 0)) %>%
      mutate(value = scale(value)) 
    model = lmer(value ~ condition + (condition || subj) + (condition || item_id), data = temp_df)
    pval = coef(summary(model))[10]
    estimate = coef(summary(model))[2]
    result_df = data.frame(word_nr = i, metric = m, pval = pval, est = estimate)
    motr_adv_stats_df = rbind(motr_adv_stats_df, result_df)
  }
}

motr_adv_plotting_df = merge(agg_motr_adv_df, motr_adv_stats_df, all=T, by = c("word_nr", "metric"))

motr_adv_plotting_df %>%
  mutate(sig = case_when( pval >= 0.05 ~ " ",
                        pval < 0.05 & pval >= 0.01  ~ "*",
                        pval < 0.01 & pval >= 0.001  ~ "**",
                        pval < 0.001  ~ "***")) %>%
  ggplot(aes(x = word_nr, y = m, color = condition)) +
    #geom_rect(aes(xmin = 2.5, xmax = 5.5, ymin = 100, ymax = 800), fill=alpha("white", 0), color = "#45ef70", linetype = "dotted") +
    geom_point() +
    geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) +
    geom_line() +
    geom_text(aes(label = sig, y = if_else(metric=="FPReg", 0, 700)), color = "black") +
    geom_text(aes(label = " ", y = if_else(metric=="FPReg", 0, 750))) +
  ylab("Reading Time") +
  xlab("Condition") +
  scale_x_continuous(breaks=-4:3, labels=c("the", "photos", "she", "took", "last/next", "week,", "but", "she")) +
  facet_wrap(.~metric, scales="free_y") +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```


```{r}

options(JULIA_HOME = "/Applications/Julia-1.8.app/Contents/Resources/julia/bin/")
library(jglmm)
jglmm_setup()

attach_lm_df = motr_attach_df %>%
  filter(metric == "gaze_duration") %>%
  filter(word_nr == 3) %>%
  mutate(item_id = as.factor(item_id),
         subj = as.factor(subj))

m = attach_lm_df %>%
  lmer(value ~ cond_id + (cond_id | item_id) + (cond_id | subj), data=.)

summary(m)


```




